from .command import CommandSchema
from .command_meal import CommandMealSchema
from .contact_message import ContactMessageSchema
from .file_serialization import FileSerialization
from .local import LocalSchema
from .meal import MealSchema
from .meal_category import MealCategorySchema
from .payment_method import PaymentMethodSchema
from .table import TableSchema
from .translation import TranslationSchema
from .user import UserSchema
