"""Add order for meal and meal category

Revision ID: 0d3e6ca924a3
Revises: efafd641aeb3
Create Date: 2021-10-28 17:55:40.453091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d3e6ca924a3'
down_revision = 'efafd641aeb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal', sa.Column('order', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'meal', ['order'])
    op.add_column('meal_category', sa.Column('order', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'meal_category', ['order'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meal_category', type_='unique')
    op.drop_column('meal_category', 'order')
    op.drop_constraint(None, 'meal', type_='unique')
    op.drop_column('meal', 'order')
    # ### end Alembic commands ###
