"""Add name, surname and lastname to user

Revision ID: 22dc6cd8701f
Revises: d99e40e1fa2f
Create Date: 2022-01-04 17:38:47.273353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22dc6cd8701f'
down_revision = 'd99e40e1fa2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('surname', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('lastname', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'surname')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
