"""Add enabled column for meal category

Revision ID: 41b5a9a52bd9
Revises: 1a4a0ed097c5
Create Date: 2021-10-29 15:26:29.527162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41b5a9a52bd9'
down_revision = '1a4a0ed097c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_category', sa.Column('enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal_category', 'enabled')
    # ### end Alembic commands ###
