"""Add imatge for payment methods

Revision ID: 564ab0206f5d
Revises: 607a265d155a
Create Date: 2021-12-06 13:57:44.618356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564ab0206f5d'
down_revision = '607a265d155a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_method', sa.Column('image', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_method', 'image')
    # ### end Alembic commands ###
