"""Added tables and enabled for user

Revision ID: 607a265d155a
Revises: 41b5a9a52bd9
Create Date: 2021-11-01 12:14:41.143979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '607a265d155a'
down_revision = '41b5a9a52bd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.add_column('command', sa.Column('table', sa.BigInteger(), nullable=True))
    op.add_column('command', sa.Column('table_name', sa.String(length=256), nullable=True))
    op.create_foreign_key(None, 'command', 'table', ['table'], ['id'], ondelete='SET NULL')
    op.add_column('user', sa.Column('enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'enabled')
    op.drop_constraint(None, 'command', type_='foreignkey')
    op.drop_column('command', 'table_name')
    op.drop_column('command', 'table')
    op.drop_table('table')
    # ### end Alembic commands ###
