"""Unique local and table number constraint

Revision ID: 7c601071d115
Revises: 4cf81a73610f
Create Date: 2021-12-09 18:39:33.946168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c601071d115'
down_revision = '4cf81a73610f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('table_number_key', 'table', type_='unique')
    op.create_unique_constraint('unique_local_and_table_number', 'table', ['local', 'number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_local_and_table_number', 'table', type_='unique')
    op.create_unique_constraint('table_number_key', 'table', ['number'])
    # ### end Alembic commands ###
