"""Added enabled and number of persons for tables

Revision ID: 7d64233f6298
Revises: 7c601071d115
Create Date: 2021-12-09 19:47:41.805163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d64233f6298'
down_revision = '7c601071d115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table', sa.Column('enabled', sa.Boolean(), nullable=False))
    op.add_column('table', sa.Column('number_of_persons', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table', 'number_of_persons')
    op.drop_column('table', 'enabled')
    # ### end Alembic commands ###
