"""Added command and command_meal extra and discount

Revision ID: 821be02b5fb9
Revises: 0d3e6ca924a3
Create Date: 2021-10-28 18:28:39.532614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '821be02b5fb9'
down_revision = '0d3e6ca924a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('command', sa.Column('discount', sa.Float(precision=2), nullable=True))
    op.add_column('command', sa.Column('extra', sa.String(length=256), nullable=True))
    op.add_column('command_meal', sa.Column('extra', sa.String(length=256), nullable=True))
    op.add_column('command_meal', sa.Column('discount', sa.Float(precision=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('command_meal', 'discount')
    op.drop_column('command_meal', 'extra')
    op.drop_column('command', 'extra')
    op.drop_column('command', 'discount')
    # ### end Alembic commands ###
