"""Added command, command_meal and payment method

Revision ID: a304cc6f39c5
Revises: 664e0ea7edcb
Create Date: 2021-10-26 21:54:08.731301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a304cc6f39c5'
down_revision = '664e0ea7edcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_method',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=124), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('command',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user', sa.BigInteger(), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('payment_method', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['payment_method'], ['payment_method.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('command_meal',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('command', sa.BigInteger(), nullable=False),
    sa.Column('meal', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['command'], ['command.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meal'], ['meal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('command_meal')
    op.drop_table('command')
    op.drop_table('payment_method')
    # ### end Alembic commands ###
