"""empty message

Revision ID: a4a15315a0d7
Revises: 22dc6cd8701f
Create Date: 2022-01-10 02:56:15.166080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4a15315a0d7'
down_revision = '22dc6cd8701f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('command', 'user',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint('command_user_fkey', 'command', type_='foreignkey')
    op.drop_constraint('command_payment_method_fkey', 'command', type_='foreignkey')
    op.create_foreign_key(None, 'command', 'user', ['user'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'command', 'payment_method', ['payment_method'], ['id'], ondelete='SET NULL')
    op.alter_column('command_meal', 'meal',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint('command_meal_meal_fkey', 'command_meal', type_='foreignkey')
    op.create_foreign_key(None, 'command_meal', 'meal', ['meal'], ['id'], ondelete='SET NULL')
    op.alter_column('table', 'local',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint('table_local_fkey', 'table', type_='foreignkey')
    op.create_foreign_key(None, 'table', 'local', ['local'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'table', type_='foreignkey')
    op.create_foreign_key('table_local_fkey', 'table', 'local', ['local'], ['id'], ondelete='CASCADE')
    op.alter_column('table', 'local',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(None, 'command_meal', type_='foreignkey')
    op.create_foreign_key('command_meal_meal_fkey', 'command_meal', 'meal', ['meal'], ['id'], ondelete='CASCADE')
    op.alter_column('command_meal', 'meal',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(None, 'command', type_='foreignkey')
    op.drop_constraint(None, 'command', type_='foreignkey')
    op.create_foreign_key('command_payment_method_fkey', 'command', 'payment_method', ['payment_method'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('command_user_fkey', 'command', 'user', ['user'], ['id'], ondelete='CASCADE')
    op.alter_column('command', 'user',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
