"""Addeed delivery to command

Revision ID: adfcc3a15718
Revises: a304cc6f39c5
Create Date: 2021-10-27 18:00:51.311754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adfcc3a15718'
down_revision = 'a304cc6f39c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('command', sa.Column('is_home_delivery', sa.Boolean(), nullable=False))
    op.add_column('command', sa.Column('delivery_address', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('command', 'delivery_address')
    op.drop_column('command', 'is_home_delivery')
    # ### end Alembic commands ###
