"""Added address details

Revision ID: d1114c438ad5
Revises: a4a15315a0d7
Create Date: 2022-01-25 16:10:31.405157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1114c438ad5'
down_revision = 'a4a15315a0d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('command', sa.Column('delivery_details', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('command', 'delivery_details')
    # ### end Alembic commands ###
