"""Add local reference to table

Revision ID: d4f56f63c6aa
Revises: 1cc77be97154
Create Date: 2021-12-09 18:19:26.894848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4f56f63c6aa'
down_revision = '1cc77be97154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table', sa.Column('local', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'table', 'local', ['local'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'table', type_='foreignkey')
    op.drop_column('table', 'local')
    # ### end Alembic commands ###
