"""empty message

Revision ID: e4f74b5818c6
Revises: b08a6a43f840
Create Date: 2021-10-19 23:54:40.582036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f74b5818c6'
down_revision = 'b08a6a43f840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_category',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('imatge_name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('meal',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=124), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('price', sa.Float(precision=2), nullable=False),
    sa.Column('category', sa.BigInteger(), nullable=True),
    sa.Column('imatge_name', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['category'], ['meal_category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal')
    op.drop_table('meal_category')
    # ### end Alembic commands ###
