"""Added translations model

Revision ID: f73c463d3a7d
Revises: 2c3ee4ca324f
Create Date: 2022-05-04 19:23:19.772826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f73c463d3a7d'
down_revision = '2c3ee4ca324f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(length=2048), nullable=False),
    sa.Column('language', sa.Enum('ES', 'CA', 'EN', name='language'), nullable=False),
    sa.Column('value', sa.String(length=2048), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'language', name='key_language_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translation')
    # ### end Alembic commands ###
